services:
  mysql:
    image: mysql:8.0
    container_name: student-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ustudent", "-pstudent123"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: student-management-app
    restart: always

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: student123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

volumes:
  mysql_data: